import assert from 'node:assert/strict';
import {canEditQueuedScreen,resolveQueuedScreen} from '../assets/shadcn-review-app/src/lib/batch-queue.mjs';
const opts={batchRunning:true,isAnalyzing:false,replacing:false,runningId:'S01'};
assert.equal(canEditQueuedScreen({id:'S01',status:'pending'},opts),false);
assert.equal(canEditQueuedScreen({id:'S02',status:'pending'},opts),true);
assert.equal(canEditQueuedScreen({id:'S03',status:'idle'},opts),true);
assert.equal(canEditQueuedScreen({id:'S04',status:'done'},opts),false);
assert.equal(canEditQueuedScreen({id:'S04',status:'done'},{...opts,batchRunning:false}),true);
const original={id:'S02',sources:{design:'old',implementation:'kept'}};
const updated={...original,sources:{design:'new',implementation:'kept'}};
const changes=new Map();
assert.equal(resolveQueuedScreen(original,changes),original);
changes.set('S02',updated);
assert.equal(resolveQueuedScreen(original,changes).sources.design,'new');
assert.equal(original.sources.design,'old');
changes.set('S02',null);
assert.equal(resolveQueuedScreen(original,changes),null);
const untouched={id:'S03',sources:{design:'other'}};
assert.equal(resolveQueuedScreen(untouched,changes),untouched);
console.log('Running group locked; pending editable; replacements resolved fresh; deleted groups skipped; unrelated sources preserved.');
